name: PyInstaller Windows

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
          
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
          
      - name: Build with PyInstaller
        run: |
          python -m PyInstaller main.spec
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: dist
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Ver ${{ github.ref_name }}
          files: |
            dist/main.exe:dist/MusicDownloadApp_V${{ github.ref_name }}.exe
